theme: jekyll-theme-minimal
title: Welcome to the eliork hompepage!
description: Feel free to bookmark this to keep an eye on my project updates! 
logo: https://github.com/eliork/eliork.github.io/blob/main/Artboard%20122.jpg
